In [5]:
# Solving ARE (Algebraic Riccati Equation) for block 1D

import numpy as np
from scipy import linalg

A = np.array([[0, 1],
              [0, 0]])

B = np.array([[0],
              [1]])

Q = np.array([[1, 0],
              [0, 1]])

R = 1

P = linalg.solve_continuous_are(A, B, Q, R)

print(P)

# проверка на совпадение в пределах погрешности
np.allclose(A.T @ P + P @ A - P @ B @ B.T @ P, -Q)



[[1.73205081 1.        ]
 [1.         1.73205081]]


True

In [8]:
# Solving ARE (Algebraic Riccati Equation) for two pendulus

import numpy as np
from scipy import linalg

m = 5.0
l = 1.0
k = 2.0
g = 10.0

A = np.array\
        ([[0,                          1, 0,                          0],
          [-(m * g + k * l) / (m * l), 0, k / m,                      0],
          [0,                          0, 0,                          1],
          [k / m,                      0, -(m * g + k * l) / (m * l), 0]])

B = np.array([[0],
              [0],
              [0],
              [1 / (m * l)]])

Q = np.eye(4)

R = np.eye(1)

P = linalg.solve_continuous_are(A, B, Q, R)

#np.set_printoptions(precision=2)
#print(x)

print(np.array_str(x, precision=2, suppress_small=True))

# проверка на совпадение в пределах погрешности
np.allclose(A.T @ P + P @ A - P @ B @ B.T @ P, -Q)

[[138.25  -0.5   -4.84  -9.62]
 [ -0.5   13.3    9.63   0.05]
 [ -4.84   9.63  70.56   0.42]
 [ -9.62   0.05   0.42   6.78]]


True